import {
  PropertyListing,
  Host,
  PropertyType,
  CategoryType,
  Amenity
} from './types';

// Helper function to generate a random number between min and max
const randomBetween = (min: number, max: number): number => {
  return Math.floor(Math.random() * (max - min + 1) + min);
};

// Helper function to generate a random rating between 4.0 and 5.0
const randomRating = (): number => {
  return Number((4 + Math.random()).toFixed(2));
};

// Helper function to format currency
export const formatCurrency = (amount: number, currency = 'USD'): string => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
  }).format(amount);
};

// Mock hosts
export const hosts: Host[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    joinDate: '2018-05-12',
    superhost: true,
    responseRate: 98,
    responseTime: 'within an hour',
    bio: 'Passionate about travel and providing exceptional experiences for my guests.',
  },
  {
    id: '2',
    name: 'Sarah Williams',
    avatar: 'https://i.pravatar.cc/150?img=5',
    joinDate: '2019-03-21',
    superhost: true,
    responseRate: 99,
    responseTime: 'within an hour',
    bio: 'Interior designer with a love for beautiful spaces and hosting travelers.',
  },
  {
    id: '3',
    name: 'Mike Chen',
    avatar: 'https://i.pravatar.cc/150?img=3',
    joinDate: '2020-11-15',
    superhost: false,
    responseRate: 90,
    responseTime: 'within a day',
    bio: 'Architect and foodie who loves sharing local tips with visitors.',
  },
  {
    id: '4',
    name: 'Emma Rodriguez',
    avatar: 'https://i.pravatar.cc/150?img=4',
    joinDate: '2017-08-30',
    superhost: true,
    responseRate: 97,
    responseTime: 'within a few hours',
    bio: 'Avid traveler and local expert who enjoys helping guests discover hidden gems.',
  },
  {
    id: '5',
    name: 'James Wilson',
    avatar: 'https://i.pravatar.cc/150?img=7',
    joinDate: '2021-02-10',
    superhost: false,
    responseRate: 85,
    responseTime: 'within a day',
    bio: 'Photographer and nature enthusiast who loves sharing experiences with travelers.',
  },
];

// Sample property categories with icons
export const categories: { name: CategoryType; icon: string; label: string }[] = [
  { name: 'trending', icon: '🔥', label: 'Trending' },
  { name: 'beachfront', icon: '🏖️', label: 'Beachfront' },
  { name: 'amazing_views', icon: '🌄', label: 'Amazing views' },
  { name: 'cabins', icon: '🏡', label: 'Cabins' },
  { name: 'castles', icon: '🏰', label: 'Castles' },
  { name: 'countryside', icon: '🌾', label: 'Countryside' },
  { name: 'design', icon: '🎨', label: 'Design' },
  { name: 'boats', icon: '⛵', label: 'Boats' },
  { name: 'tropical', icon: '🌴', label: 'Tropical' },
  { name: 'skiing', icon: '⛷️', label: 'Skiing' },
  { name: 'mansions', icon: '🏛️', label: 'Mansions' },
  { name: 'luxury', icon: '💎', label: 'Luxury' },
];

// Sample amenities with icons
export const amenityIcons: Record<Amenity, { icon: string; label: string }> = {
  wifi: { icon: 'wifi', label: 'WiFi' },
  tv: { icon: 'tv', label: 'TV' },
  kitchen: { icon: 'utensils', label: 'Kitchen' },
  washer: { icon: 'wind', label: 'Washer' },
  dryer: { icon: 'droplet', label: 'Dryer' },
  ac: { icon: 'fan', label: 'Air conditioning' },
  heating: { icon: 'thermometer', label: 'Heating' },
  pool: { icon: 'droplets', label: 'Pool' },
  hot_tub: { icon: 'bath', label: 'Hot tub' },
  free_parking: { icon: 'car', label: 'Free parking' },
  gym: { icon: 'dumbbell', label: 'Gym' },
  breakfast: { icon: 'coffee', label: 'Breakfast' },
  workspace: { icon: 'briefcase', label: 'Workspace' },
  pets_allowed: { icon: 'cat', label: 'Pets allowed' },
  smoking_allowed: { icon: 'cigarette', label: 'Smoking allowed' },
  beachfront: { icon: 'umbrella', label: 'Beachfront' },
  waterfront: { icon: 'waves', label: 'Waterfront' },
  ski_in_out: { icon: 'skiing', label: 'Ski-in/Ski-out' },
};

// Generate mock property listings
export const properties: PropertyListing[] = [
  {
    id: '1',
    title: 'Luxurious Beachfront Villa with Infinity Pool',
    description: 'Experience the ultimate luxury getaway at this stunning beachfront villa. Enjoy breathtaking ocean views from the private infinity pool and direct beach access. The spacious interior features modern design with local touches, fully equipped kitchen, and premium amenities throughout.',
    host: hosts[0],
    location: {
      city: 'Bali',
      country: 'Indonesia',
      lat: -8.4095,
      lng: 115.1889,
    },
    images: [
      {
        id: '101',
        url: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '102',
        url: 'https://images.unsplash.com/photo-1613553507747-5f8d62ad5904?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '103',
        url: 'https://images.unsplash.com/photo-1615880484746-a134be9a6ecf?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '104',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '105',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 450,
      cleaningFee: 85,
      serviceFee: 95,
      total: 630,
      currency: 'USD',
    },
    propertyType: 'villa',
    category: ['beachfront', 'luxury', 'amazing_views'],
    amenities: ['wifi', 'pool', 'kitchen', 'ac', 'free_parking', 'waterfront', 'beachfront', 'hot_tub', 'tv'],
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 4.5,
    rating: 4.98,
    reviewCount: 124,
    instantBook: true,
    superhost: true,
    featured: true,
  },
  {
    id: '2',
    title: 'Modern Mountain Cabin with Hot Tub',
    description: 'Escape to this stylish mountain cabin featuring a private hot tub with forest views. Surrounded by nature yet only 15 minutes from town, it offers the perfect balance of seclusion and convenience. Warm, contemporary interior with a wood-burning fireplace and full amenities for a cozy mountain getaway.',
    host: hosts[1],
    location: {
      city: 'Aspen',
      state: 'Colorado',
      country: 'United States',
      lat: 39.1911,
      lng: -106.8175,
    },
    images: [
      {
        id: '201',
        url: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '202',
        url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '203',
        url: 'https://images.unsplash.com/photo-1517511620798-cec17d428bc0?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '204',
        url: 'https://images.unsplash.com/photo-1604014555737-78e7e1316137?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 295,
      cleaningFee: 65,
      serviceFee: 70,
      total: 430,
      currency: 'USD',
    },
    propertyType: 'cabin',
    category: ['amazing_views', 'cabins', 'trending'],
    amenities: ['wifi', 'kitchen', 'heating', 'hot_tub', 'free_parking', 'tv', 'workspace'],
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    rating: 4.92,
    reviewCount: 86,
    instantBook: true,
    superhost: true,
  },
  {
    id: '3',
    title: 'Historic Castle Suite with Panoramic Views',
    description: 'Stay in an authentic renovated medieval castle with modern luxuries. This private suite offers stunning views of the countryside, a four-poster bed, and access to the castle grounds including gardens and a small lake. Experience the perfect blend of history and comfort.',
    host: hosts[4],
    location: {
      city: 'Edinburgh',
      country: 'United Kingdom',
      lat: 55.9533,
      lng: -3.1883,
    },
    images: [
      {
        id: '301',
        url: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?q=80&w=2348&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '302',
        url: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '303',
        url: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?q=80&w=2274&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 380,
      cleaningFee: 75,
      serviceFee: 85,
      total: 540,
      currency: 'USD',
    },
    propertyType: 'castle',
    category: ['castles', 'trending', 'countryside'],
    amenities: ['wifi', 'heating', 'breakfast', 'tv'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.88,
    reviewCount: 52,
    instantBook: false,
    superhost: false,
  },
  {
    id: '4',
    title: 'Minimalist Design Loft in Art District',
    description: 'Immerse yourself in this architecturally stunning loft in the heart of the arts district. High ceilings, industrial elements, and modern furnishings create a sophisticated urban retreat. Walking distance to galleries, restaurants, and nightlife.',
    host: hosts[2],
    location: {
      city: 'Barcelona',
      country: 'Spain',
      lat: 41.3851,
      lng: 2.1734,
    },
    images: [
      {
        id: '401',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '402',
        url: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=2342&auto=format&fit=crop',
      },
      {
        id: '403',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 180,
      cleaningFee: 45,
      serviceFee: 40,
      total: 265,
      currency: 'USD',
    },
    propertyType: 'apartment',
    category: ['design', 'trending'],
    amenities: ['wifi', 'kitchen', 'ac', 'tv', 'workspace'],
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    rating: 4.85,
    reviewCount: 78,
    instantBook: true,
    superhost: false,
  },
  {
    id: '5',
    title: 'Tropical Treehouse Retreat with Ocean View',
    description: 'Experience unique accommodations in this handcrafted treehouse surrounded by lush tropical forest with ocean views. Fall asleep to the sounds of nature and wake up to birdsong. Beautifully designed with local materials and an outdoor shower. A truly magical experience.',
    host: hosts[3],
    location: {
      city: 'Tulum',
      country: 'Mexico',
      lat: 20.2114,
      lng: -87.4654,
    },
    images: [
      {
        id: '501',
        url: 'https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?q=80&w=2342&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '502',
        url: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '503',
        url: 'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?q=80&w=2271&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 225,
      cleaningFee: 50,
      serviceFee: 55,
      total: 330,
      currency: 'USD',
    },
    propertyType: 'treehouse',
    category: ['tropical', 'amazing_views', 'trending'],
    amenities: ['wifi', 'beachfront', 'waterfront'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.97,
    reviewCount: 43,
    instantBook: false,
    superhost: true,
  },
  {
    id: '6',
    title: 'Sleek Downtown Apartment with City Skyline Views',
    description: 'Modern high-rise apartment with floor-to-ceiling windows offering spectacular city views. Contemporary furnishings, full amenities, and a gourmet kitchen make this the perfect urban getaway. Building features include gym, rooftop lounge, and 24-hour security.',
    host: hosts[1],
    location: {
      city: 'Tokyo',
      country: 'Japan',
      lat: 35.6762,
      lng: 139.6503,
    },
    images: [
      {
        id: '601',
        url: 'https://images.unsplash.com/photo-1551361415-69c87624334f?q=80&w=2342&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '602',
        url: 'https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '603',
        url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 195,
      cleaningFee: 60,
      serviceFee: 50,
      total: 305,
      currency: 'USD',
    },
    propertyType: 'apartment',
    category: ['design', 'amazing_views'],
    amenities: ['wifi', 'kitchen', 'ac', 'gym', 'tv', 'workspace'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.89,
    reviewCount: 105,
    instantBook: true,
    superhost: true,
  },
  {
    id: '7',
    title: 'Charming Vineyard Cottage in Wine Country',
    description: 'Located on a working vineyard, this renovated stone cottage offers a peaceful retreat surrounded by rolling hills and grapevines. Enjoy wine tasting, countryside walks, and stunning sunsets from your private terrace. Includes a welcome bottle from the estate.',
    host: hosts[0],
    location: {
      city: 'Bordeaux',
      country: 'France',
      lat: 44.8378,
      lng: -0.5792,
    },
    images: [
      {
        id: '701',
        url: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?q=80&w=2232&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '702',
        url: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '703',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2053&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 210,
      cleaningFee: 55,
      serviceFee: 53,
      total: 318,
      currency: 'USD',
    },
    propertyType: 'house',
    category: ['countryside', 'amazing_views'],
    amenities: ['wifi', 'kitchen', 'free_parking', 'heating', 'tv'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    rating: 4.95,
    reviewCount: 67,
    instantBook: false,
    superhost: true,
  },
  {
    id: '8',
    title: 'Floating Houseboat with Water Views',
    description: 'Experience life on the water in this charming houseboat. Gentle rocking motions and water views from every window create a uniquely relaxing stay. Recently renovated with modern comforts while maintaining maritime character.',
    host: hosts[2],
    location: {
      city: 'Amsterdam',
      country: 'Netherlands',
      lat: 52.3676,
      lng: 4.9041,
    },
    images: [
      {
        id: '801',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=2274&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '802',
        url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '803',
        url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=2274&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 175,
      cleaningFee: 45,
      serviceFee: 43,
      total: 263,
      currency: 'USD',
    },
    propertyType: 'boat',
    category: ['boats', 'waterfront', 'trending'],
    amenities: ['wifi', 'kitchen', 'heating', 'waterfront', 'tv'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.87,
    reviewCount: 92,
    instantBook: true,
    superhost: false,
  },
  {
    id: '9',
    title: 'Rustic Barn Conversion with Meadow Views',
    description: 'Stay in this beautifully converted barn surrounded by rolling meadows. Exposed beams and stone walls blend with modern comforts, including a spacious kitchen and outdoor fire pit. Perfect for a peaceful countryside escape.',
    host: hosts[2],
    location: {
      city: 'Tuscany',
      country: 'Italy',
      lat: 43.7711,
      lng: 11.2486,
    },
    images: [
      {
        id: '901',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '902',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '903',
        url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 185,
      cleaningFee: 50,
      serviceFee: 45,
      total: 280,
      currency: 'USD',
    },
    propertyType: 'house',
    category: ['countryside', 'design'],
    amenities: ['wifi', 'kitchen', 'heating', 'free_parking', 'pets_allowed'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1.5,
    rating: randomRating(),
    reviewCount: 62,
    instantBook: true,
    superhost: false,
  },
  {
    id: '10',
    title: 'Oceanfront Bungalow with Private Beach',
    description: 'Wake up to the sound of waves in this cozy oceanfront bungalow. Step directly onto your private stretch of beach or relax on the shaded porch with panoramic sea views. Ideal for a romantic getaway or small family retreat.',
    host: hosts[0],
    location: {
      city: 'Maui',
      state: 'Hawaii',
      country: 'United States',
      lat: 20.7984,
      lng: -156.3319,
    },
    images: [
      {
        id: '1001',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '1002',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '1003',
        url: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 320,
      cleaningFee: 70,
      serviceFee: 75,
      total: 465,
      currency: 'USD',
    },
    propertyType: 'bungalow',
    category: ['beachfront', 'tropical', 'amazing_views'],
    amenities: ['wifi', 'kitchen', 'ac', 'beachfront', 'waterfront', 'tv'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    rating: randomRating(),
    reviewCount: 95,
    instantBook: false,
    superhost: true,
  },
  {
    id: '11',
    title: 'Ski-In/Ski-Out Condo with Mountain Views',
    description: 'Hit the slopes from this modern condo with direct ski access. After a day of skiing, unwind by the fireplace or enjoy the shared hot tub and gym. Stunning alpine views from every room.',
    host: hosts[1],
    location: {
      city: 'Whistler',
      state: 'British Columbia',
      country: 'Canada',
      lat: 50.1163,
      lng: -122.9574,
    },
    images: [
      {
        id: '1101',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '1102',
        url: 'https://images.unsplash.com/photo-1571931468289-597a0dbf7f0e?q=80&w=2340&auto=format&fit=crop',
      },
      {
        id: '1103',
        url: 'https://images.unsplash.com/photo-1601919051950-81d990bc1396?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 350,
      cleaningFee: 80,
      serviceFee: 85,
      total: 515,
      currency: 'USD',
    },
    propertyType: 'condo',
    category: ['skiing', 'amazing_views'],
    amenities: ['wifi', 'kitchen', 'hot_tub', 'gym', 'ski_in_out', 'heating', 'tv'],
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    rating: randomRating(),
    reviewCount: 78,
    instantBook: true,
    superhost: true,
  },
  {
    id: '12',
    title: 'Artistic Loft in Historic Warehouse',
    description: 'Live like a local in this creatively designed loft within a converted warehouse. High ceilings, exposed brick, and bold artwork define this urban oasis. Steps away from trendy cafes and art galleries.',
    host: hosts[3],
    location: {
      city: 'New York',
      state: 'New York',
      country: 'United States',
      lat: 40.7128,
      lng: -74.0060,
    },
    images: [
      {
        id: '1201',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2340&auto=format&fit=crop',
        isPrimary: true,
      },
      {
        id: '1202',
        url: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=2342&auto=format&fit=crop',
      },
      {
        id: '1203',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2340&auto=format&fit=crop',
      },
    ],
    price: {
      basePrice: 240,
      cleaningFee: 55,
      serviceFee: 60,
      total: 355,
      currency: 'USD',
    },
    propertyType: 'apartment',
    category: ['design', 'trending'],
    amenities: ['wifi', 'kitchen', 'ac', 'workspace', 'tv'],
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    rating: randomRating(),
    reviewCount: 110,
    instantBook: true,
    superhost: false,
  },
  {
    id: '13',
    title: 'Traditional Japanese Ryokan with Onsen',
    description: 'Immerse yourself in Japanese culture at this authentic ryokan featuring a private onsen (hot spring). Tatami mats, futon beds, and a kaiseki dinner option create a tranquil, traditional experience.',
    host: hosts[4],
    location: {
      city: 'Kyoto',
      country: 'Japan',
      lat: 35.0116,
      lng: 135.7681,
    },
    images: [
      {
        id: '1301',
        url: 'https://imgs.search.brave.com/CC6ZZIoABK1nWvmY__bQhnhM1sgJ_juEDxayagUcCoQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMudm9ndWUuY29t/L3Bob3Rvcy81YTMx/NTE3OTcxNTA5MDY3/MTU4NDE5ZjcvbWFz/dGVyL3dfMTYwMCxj/X2xpbWl0L25pc2hp/bXVyYXlhLWhvbmth/bi1yeW9rYW4ta2lu/b3Nha2ktb25zZW4u/anBn',
        isPrimary: true,
      },
      {
        id: '1302',
        url: 'https://imgs.search.brave.com/vVKOoCdiPR270M53JiW4Xj-wN2-QNQayGawaZwm9wWg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc3F1YXJlc3Bh/Y2UtY2RuLmNvbS9j/b250ZW50L3YxLzVl/MDE5Mzk3YTdhOWY0/MjMyZTQyOGU0My8x/NjA4Nzk5Mzk2NzAx/LTY1M1ZFQlNSWTI3/VU8wVTk3WUgwL3l1/dWthZW4wMDEuanBn',
      },
      {
        id: '1303',
        url: 'https://imgs.search.brave.com/hXaZ-BJ2_VTiHOCUGFMaMlIt8qlPxN3r-qCm7vNBzg8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy8y/LzI3L1RhbWF0c3Vr/dXJpX29uc2VuX3lh/ZG8wMnMzNjQ4Lmpw/Zw',
      },
    ],
    price: {
      basePrice: 290,
      cleaningFee: 65,
      serviceFee: 70,
      total: 425,
      currency: 'USD',
    },
    propertyType: 'ryokan',
    category: ['luxury', 'trending'],
    amenities: ['wifi', 'hot_tub', 'breakfast', 'heating'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 4,
    bathrooms: 1,
    rating: randomRating(),
    reviewCount: 53,
    instantBook: false,
    superhost: true,
  },
  {
    id: '14',
    title: 'Clifftop Cottage with Coastal Views',
    description: 'Perched on a cliff overlooking the sea, this charming cottage offers dramatic ocean vistas and coastal hiking trails nearby. Cozy up by the wood stove or enjoy the sunset from the private patio.',
    host: hosts[1],
    location: {
      city: 'Big Sur',
      state: 'California',
      country: 'United States',
      lat: 36.2704,
      lng: -121.8081,
    },
    images: [
      {
        id: '1401',
        url: 'https://imgs.search.brave.com/OZgCmze8AEZy99KVA6SWlaOaWdWZP5ccP8SLYpPY2qs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMi1w/cm9kLndhbGVzb25s/aW5lLmNvLnVrL25l/d3MvdWstbmV3cy9h/cnRpY2xlMjg3MTAw/NDMuZWNlL0FMVEVS/TkFURVMvczYxNWIv/MV9zaG9ydGxpc3Qw/MS5qcGc',
        isPrimary: true,
      },
      {
        id: '1402',
        url: 'https://imgs.search.brave.com/5dJySko5ypYtKWkRQRSA1uPwuuckcNAzuuHg3CoBnvc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/cGVyZmVjdHN0YXlz/LmNvLnVrL2ltYWdl/X2NhY2hlL2MvYy8y/LzIvMS9jYzIyMThk/YTEzNmZjNWVlNzFl/NTkxY2RiMDAwZjE5/ZTY0NWYwM2NkLmpw/ZWc',
      },
      {
        id: '1403',
        url: 'https://imgs.search.brave.com/gn0vBCdPNZvnbxZ8s7yP5H4o9pVNyt_Z8ILWJWjNxKs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dGhlcG9ydHNlYWNh/bXAuY29tLmF1L3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L1BvcnRzZWFDYW1w/RmFjaWxpdGllcy0w/MjAtc2NhbGVkLXVh/aS0yNTYweDE0NDAu/anBn',
      },
    ],
    price: {
      basePrice: 275,
      cleaningFee: 60,
      serviceFee: 65,
      total: 400,
      currency: 'USD',
    },
    propertyType: 'cottage',
    category: ['amazing_views', 'beachfront'],
    amenities: ['wifi', 'kitchen', 'heating', 'free_parking', 'waterfront'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: randomRating(),
    reviewCount: 67,
    instantBook: true,
    superhost: true,
  },
  {
    id: '15',
    title: 'Spacious Mansion with Private Pool',
    description: 'Indulge in luxury at this grand mansion featuring a private pool, manicured gardens, and elegant interiors. Perfect for large groups or special occasions, with ample space and top-tier amenities.',
    host: hosts[0],
    location: {
      city: 'Palm Springs',
      state: 'California',
      country: 'United States',
      lat: 33.8303,
      lng: -116.5453,
    },
    images: [
      {
        id: '1501',
        url: 'https://imgs.search.brave.com/dReMeCp0OmEno9nNWDj73OQgPsBlraG26PqIS3gARa0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA3Lzk4LzI5LzE4/LzM2MF9GXzc5ODI5/MTg5OV9KYlF1cDFG/T0o5UlJXYkY3SG9K/VHZRNW5YelpPcHpD/VC5qcGc',
        isPrimary: true,
      },
      {
        id: '1502',
        url: 'https://imgs.search.brave.com/OCngKcw9SYGxSMYKtU5UOwR798p0tJqFvzbnZ95j424/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5hcmNoaXRlY3R1/cmFsZGlnZXN0LmNv/bS9waG90b3MvNjdj/NzQ4OGZmZDRiZWEy/ZGJmYjdhODM5LzE6/MS9wYXNzL3VuZGVm/aW5lZA',
      },
      {
        id: '1503',
        url: 'https://imgs.search.brave.com/k7HP7FFCYtPkKoEKmYzuhhinwwDpDJI_hjAk3KM6edQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA3LzU5LzE2LzAz/LzM2MF9GXzc1OTE2/MDM0OV9UeEVxdmxK/akp0TUE0NEw5em1B/WDB2bmg4VzVHTWNy/OS5qcGc',
      },
    ],
    price: {
      basePrice: 650,
      cleaningFee: 120,
      serviceFee: 130,
      total: 900,
      currency: 'USD',
    },
    propertyType: 'mansion',
    category: ['mansions', 'luxury', 'trending'],
    amenities: ['wifi', 'pool', 'kitchen', 'ac', 'free_parking', 'gym', 'tv'],
    maxGuests: 12,
    bedrooms: 6,
    beds: 8,
    bathrooms: 4, // Corrected from false to 4
    rating: randomRating(),
    reviewCount: 45,
    instantBook: false,
    superhost: true,
  },
  {
    id: '16',
    title: 'Cozy Shepherd’s Hut in the Highlands',
    description: 'Escape to this charming shepherd’s hut in the rugged Scottish Highlands. Compact yet comfortable, with a wood-burning stove and breathtaking mountain views. Ideal for nature lovers seeking solitude.',
    host: hosts[4],
    location: {
      city: 'Glencoe',
      country: 'United Kingdom',
      lat: 56.6827,
      lng: -5.1034,
    },
    images: [
      {
        id: '1601',
        url: 'https://imgs.search.brave.com/dzIjbgdigK_91TIRDpPhmlaJcjWSf8hvX1aOs2wIUBo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb29s/c3RheXMuaW1naXgu/bmV0LzIzNTgyMi5q/cGc_JnZpYj0wJmhp/Z2g9MCZzaGFkPTAm/c2F0PTAmZXhwPTAm/YnJpPTAmY29uPTAm/c2hhcnA9MCZmcC14/PTAuNSZmcC15PTAu/NSZmcC16PTEmcm90/PTAmdz01MTAmaD0z/NDAmZml0PWNyb3Am/Y3JvcD1mb2NhbHBv/aW50JnE9NTA', // Exterior of a shepherd's hut in highlands
        isPrimary: true,
      },
      {
        id: '1602',
        url: 'https://imgs.search.brave.com/T9Qb8PQqL3wI9LTs4uHEOjC_jPc9Iy7JAPtqEkKwO-c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y3JhYnRyZWVhbmRj/cmFidHJlZS5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjQv/MDgvV2FndGFpbC1T/aGVwaGVyZHMtSHV0/LUNyYWJ0cmVlLUNy/YWJ0cmVlLTEuanBn', // Interior of a cozy hut
      },
      {
        id: '1603',
        url: 'https://imgs.search.brave.com/Ai55BaReMBr43F_o6aTBRBXaAwA53V1CniGnxL-v2_0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZXRy/by5jby51ay93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyNC8wMy9U/aWx0b24tSHV0cy1M/ZWljZXN0ZXJzaGly/ZTIwLTM0MGQuanBn/P3F1YWxpdHk9OTAm/c3RyaXA9YWxsJnc9/NjQ2', // Highland landscape view
      },
    ],
    price: {
      basePrice: 130,
      cleaningFee: 35,
      serviceFee: 30,
      total: 195,
      currency: 'USD',
    },
    propertyType: 'hut',
    category: ['countryside', 'amazing_views'],
    amenities: ['heating', 'free_parking'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 0.5,
    rating: randomRating(),
    reviewCount: 28,
    instantBook: true,
    superhost: true,
  },
  // {
  //   id: '17',
  //   title: 'Modern Yacht in Marina Bay',
  //   description: 'Live aboard this sleek yacht docked in a vibrant marina. Enjoy water views, a sundeck, and easy access to waterfront dining and nightlife. A unique floating getaway.',
  //   host: hosts[2],
  //   location: {
  //     city: 'Miami',
  //     state: 'Florida',
  //     country: 'United States',
  //     lat: 25.7617,
  //     lng: -80.1918,
  //   },
  //   images: [
  //     {
  //       id: '1701',
  //       url: 'https://images.unsplash.com/photo-1563911596931-8e5f32d32e07?q=80&w=2340&auto=format&fit=crop', // Yacht exterior in marina
  //       isPrimary: true,
  //     },
  //     {
  //       id: '1702',
  //       url: 'https://images.unsplash.com/photo-1590874109175-36d57e715388?q=80&w=2340&auto=format&fit=crop', // Yacht interior
  //     },
  //     {
  //       id: '1703',
  //       url: 'https://images.unsplash.com/photo-1566498094815-8b90f4f2e1b1?q=80&w=2340&auto=format&fit=crop', // Marina bay view
  //     },
  //   ],
  //   price: {
  //     basePrice: 280,
  //     cleaningFee: 60,
  //     serviceFee: 65,
  //     total: 405,
  //     currency: 'USD',
  //   },
  //   propertyType: 'boat',
  //   category: ['boats', 'waterfront', 'luxury'],
  //   amenities: ['wifi', 'kitchen', 'ac', 'tv', 'waterfront'],
  //   maxGuests: 6,
  //   bedrooms: 3,
  //   beds: 3,
  //   bathrooms: 2,
  //   rating: randomRating(),
  //   reviewCount: 84,
  //   instantBook: true,
  //   superhost: false,
  // },
  // {
  //   id: '18',
  //   title: 'Safari Tent in the Savanna',
  //   description: 'Experience the wild in this luxurious safari tent surrounded by savanna landscapes. Watch wildlife from your private deck and enjoy guided tours. A blend of adventure and comfort.',
  //   host: hosts[3],
  //   location: {
  //     city: 'Serengeti',
  //     country: 'Tanzania',
  //     lat: -2.1539,
  //     lng: 34.6857,
  //   },
  //   images: [
  //     {
  //       id: '1801',
  //       url: 'https://images.unsplash.com/photo-1518998053906-4d7e6b5e8b44?q=80&w=2340&auto=format&fit=crop', // Safari tent exterior
  //       isPrimary: true,
  //     },
  //     {
  //       id: '1802',
  //       url: 'https://images.unsplash.com/photo-1589909202802-8f1a8d9ec52e?q=80&w=2340&auto=format&fit=crop', // Interior of a luxury tent
  //     },
  //     {
  //       id: '1803',
  //       url: 'https://images.unsplash.com/photo-1518709268805-4e9042af5929?q=80&w=2340&auto=format&fit=crop', // Savanna landscape with wildlife
  //     },
  //   ],
  //   price: {
  //     basePrice: 400,
  //     cleaningFee: 80,
  //     serviceFee: 90,
  //     total: 570,
  //     currency: 'USD',
  //   },
  //   propertyType: 'tent',
  //   category: ['trending', 'luxury', 'countryside'],
  //   amenities: ['breakfast', 'free_parking', 'pets_allowed'],
  //   maxGuests: 4,
  //   bedrooms: 2,
  //   beds: 2,
  //   bathrooms: 1,
  //   rating: randomRating(),
  //   reviewCount: 36,
  //   instantBook: false,
  //   superhost: true,
  // }
];
